export const merchantFundRecords = [
  {
    orderType: "Payin",
    orderId: "order_id_1",
    balanceType: "Merchant balance",
    balanceBefore: "100",
    amount: "110",
    balanceAfter: "210",
    description: "Order amount: 110, Agent commission: 1",
    createdAt: new Date(),
  },
  {
    orderType: "Payin",
    orderId: "order_id_1",
    balanceType: "Member commission",
    balanceBefore: "100",
    amount: "110",
    balanceAfter: "210",
    description: "Order amount: 110, Agent commission: 1",
    createdAt: new Date(),
  },
  {
    orderType: "Payin",
    orderId: "order_id_1",
    balanceType: "Agent commission",
    balanceBefore: "100",
    amount: "110",
    balanceAfter: "210",
    description: "Order amount: 110, Agent commission: 1",
    createdAt: new Date(),
  },
  {
    orderType: "Payin",
    orderId: "order_id_1",
    balanceType: "Member quota",
    balanceBefore: "100",
    amount: "110",
    balanceAfter: "210",
    description: "Order amount: 110, Agent commission: 1",
    createdAt: new Date(),
  },
  {
    orderType: "Payin",
    orderId: "order_id_1",
    balanceType: "System balance",
    balanceBefore: "100",
    amount: "110",
    balanceAfter: "210",
    description: "Order amount: 110, Agent commission: 1",
    createdAt: new Date(),
  },
  {
    orderType: "Payin",
    orderId: "order_id_1",
    balanceType: "Gateway charge",
    balanceBefore: "100",
    amount: "110",
    balanceAfter: "210",
    description: "Order amount: 110, Agent commission: 1",
    createdAt: new Date(),
  },
];
